// 図鑑に載る生き物たち。rarity は 1〜3（★の数）。
export const SPECIES = [
  {
    id: 'anthias',
    name: 'キンギョハナダイ',
    sci: 'Pseudanthias squamipinnis',
    size: '約 12 cm',
    depth: '3〜20 m',
    area: 'サンゴの庭・マンタの根',
    rarity: 1,
    text: 'サンゴ礁の上でオレンジ色の群れをつくる小さな魚。群れのほとんどはメスで、メスが性転換してオスになる。',
  },
  {
    id: 'damsel',
    name: 'ルリスズメダイ',
    sci: 'Chrysiptera cyanea',
    size: '約 8 cm',
    depth: '1〜10 m',
    area: 'サンゴの庭',
    rarity: 1,
    text: '宝石のような瑠璃色の小さなスズメダイ。枝サンゴのすき間を住みかにしていて、近づくとさっと隠れる。',
  },
  {
    id: 'clown',
    name: 'カクレクマノミ',
    sci: 'Amphiprion ocellaris',
    size: '約 9 cm',
    depth: '1〜15 m',
    area: 'サンゴの庭（イソギンチャク）',
    rarity: 1,
    text: 'イソギンチャクと共生するクマノミの仲間。体をおおう粘液のおかげで、イソギンチャクの毒針に刺されない。',
  },
  {
    id: 'tang',
    name: 'ナンヨウハギ',
    sci: 'Paracanthurus hepatus',
    size: '約 25 cm',
    depth: '2〜40 m',
    area: 'サンゴの庭',
    rarity: 1,
    text: '鮮やかな青と黒の模様に黄色い尾。ニザダイの仲間で、尾の付け根に刃物のような鋭いトゲを隠し持つ。',
  },
  {
    id: 'idol',
    name: 'ツノダシ',
    sci: 'Zanclus cornutus',
    size: '約 20 cm',
    depth: '3〜60 m',
    area: 'サンゴの庭・沈んだ神殿',
    rarity: 1,
    text: '長く伸びた背びれと、黒・白・黄の帯模様が目印。仲間のいない一科一属一種の魚。',
  },
  {
    id: 'butterfly',
    name: 'チョウチョウウオ',
    sci: 'Chaetodon auripes',
    size: '約 18 cm',
    depth: '1〜30 m',
    area: 'サンゴの庭',
    rarity: 1,
    text: '黄色い体に細いしま模様。目を通る黒い帯は、敵に目の位置をわかりにくくするためと考えられている。よく二匹で泳ぐ。',
  },
  {
    id: 'fusilier',
    name: 'グルクン（タカサゴ）',
    sci: 'Pterocaesio digramma',
    size: '約 30 cm',
    depth: '5〜40 m',
    area: 'マンタの根',
    rarity: 1,
    text: '中層で大きな群れをつくって泳ぐ。沖縄では「県の魚」に選ばれている、なじみ深い魚。',
  },
  {
    id: 'trevally',
    name: 'ギンガメアジ',
    sci: 'Caranx sexfasciatus',
    size: '約 70 cm',
    depth: '5〜60 m',
    area: 'マンタの根',
    rarity: 2,
    text: '銀色に光るアジの仲間。昼間は何百匹もの大群で、竜巻のように渦を巻いて泳ぐことがある。',
  },
  {
    id: 'sweeper',
    name: 'キンメモドキ',
    sci: 'Parapriacanthus ransonneti',
    size: '約 10 cm',
    depth: '5〜30 m',
    area: '青の洞窟',
    rarity: 2,
    text: '洞窟や岩陰に大群でくらす小さな魚。光が当たると、体が金色に透けて見える。',
  },
  {
    id: 'puffer',
    name: 'ハリセンボン',
    sci: 'Diodon holocanthus',
    size: '約 30 cm',
    depth: '2〜30 m',
    area: 'サンゴの庭・沈んだ神殿',
    rarity: 2,
    text: 'おどろくと水を吸いこんで体をふくらませ、トゲを立てて身を守る。トゲの数は千本ではなく、三百数十本ほど。',
  },
  {
    id: 'napoleon',
    name: 'メガネモチノウオ',
    sci: 'Cheilinus undulatus',
    size: '約 1.5 m',
    depth: '5〜60 m',
    area: '沈んだ神殿',
    rarity: 2,
    text: '通称ナポレオンフィッシュ。こぶのように張り出した額が特徴で、ベラの仲間では最大級。2 m 近くになる。',
  },
  {
    id: 'moray',
    name: 'ウツボ',
    sci: 'Gymnothorax sp.',
    size: '約 80 cm',
    depth: '1〜40 m',
    area: '沈んだ神殿（西の壁の穴）',
    rarity: 2,
    text: '岩のすき間から顔を出している。口をぱくぱく開け閉めするのは威嚇ではなく、えらに水を送って呼吸するため。',
  },
  {
    id: 'whitetip',
    name: 'ネムリブカ',
    sci: 'Triaenodon obesus',
    size: '約 1.6 m',
    depth: '8〜40 m',
    area: '青の洞窟',
    rarity: 2,
    text: '昼間は洞窟の奥や岩陰の海底でじっと休んでいるサメ。夜になると活発に狩りをする。',
  },
  {
    id: 'turtle',
    name: 'アオウミガメ',
    sci: 'Chelonia mydas',
    size: '甲羅 約 1 m',
    depth: '0〜20 m',
    area: 'サンゴの庭（海草の原）',
    rarity: 2,
    text: '海草や海藻を食べる草食のウミガメ。体の脂肪が緑色をしていることが名前の由来。ときどき水面へ息つぎに上がる。',
  },
  {
    id: 'manta',
    name: 'ナンヨウマンタ',
    sci: 'Mobula alfredi',
    size: '横幅 約 4 m',
    depth: '3〜40 m',
    area: 'マンタの根',
    rarity: 2,
    text: '翼のような胸びれを広げて、ゆったりと空を飛ぶように泳ぐ。大きなものは 5 m 近くになり、プランクトンを食べる。',
  },
  {
    id: 'eagleray',
    name: 'マダラトビエイ',
    sci: 'Aetobatus ocellatus',
    size: '横幅 約 2 m',
    depth: '1〜60 m',
    area: '沈んだ神殿',
    rarity: 2,
    text: '背中の白い水玉模様と、むちのように長い尾が特徴のエイ。砂の中の貝を掘り出して、かたい殻ごとかみ砕く。',
  },
  {
    id: 'jelly',
    name: 'ミズクラゲ',
    sci: 'Aurelia sp.',
    size: '傘 約 20 cm',
    depth: '0〜10 m',
    area: 'ボートのまわり',
    rarity: 1,
    text: '傘の中に透けて見える四つの輪（生殖腺）が目印。刺す力は弱く、ゆっくりと拍動しながら漂う。',
  },
  {
    id: 'dolphin',
    name: 'ミナミハンドウイルカ',
    sci: 'Tursiops aduncus',
    size: '約 2.5 m',
    depth: '0〜20 m',
    area: '入り江の浅いところ',
    rarity: 3,
    text: '群れでくらす好奇心の強いイルカ。ときどき水面から高くジャンプする。出会えたら幸運。',
  },
  {
    id: 'whaleshark',
    name: 'ジンベエザメ',
    sci: 'Rhincodon typus',
    size: '約 8 m',
    depth: '0〜（深い外洋）',
    area: '外洋の崖',
    rarity: 3,
    text: '世界最大の魚。10 m を超えることもある。大きな口で海水ごとプランクトンを吸いこむ、おとなしい性格。',
  },
  {
    id: 'clam',
    name: 'シャコガイ',
    sci: 'Tridacna sp.',
    size: '約 50 cm',
    depth: '1〜20 m',
    area: 'サンゴの庭',
    rarity: 1,
    text: 'サンゴ礁にすむ大きな二枚貝。色あざやかな外套膜に褐虫藻をすまわせ、その光合成から栄養をもらっている。',
  },
];

export const SPECIES_BY_ID = Object.fromEntries(SPECIES.map((s, i) => [s.id, { ...s, no: i + 1 }]));
